### ISSUE TITLE
Consider tiling to query images efficiently

### ISSUE THREAD

**Issue by stuaxo** [Phildo/pixQL#1]
When it comes to handling other formats you will want to decide how to keep them in memory, I suggest using tiling:

The gimp uses (or used) to use tiles to handle images efficiently 

http://www.gimp.org/docs/plug-in/sect-tiles.html

Tiling achieves good performance because locality is maintained, it might be worth considering such a system for any queries that are not purely linear.

Possibly which way the image is laid out could be decided in your query planning stage (if you have one).

**Comment by Phildo** [comment]
Alright. I dig the suggestion. Thanks!
