### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Phildo/pixQL#5]
I would like to point out that identifiers like "[`_BITMAP_H_`](https://github.com/Phildo/pixQL/blob/49b309ba4a7055c776528a1cd4bcb40f23612d1f/bitmap.h#L1)" and "[`_PIX_H_`](https://github.com/Phildo/pixQL/blob/0b8f8328fa172d915a65ea3e293f39dd835f2943/pix.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Phildo** [comment]
Thanks! I had no idea. Will do when I get home (at work, atm, hah). :)

**Comment by elfring** [comment]
Would it be better to keep this bug report open until it will be really fixed?

**Comment by Phildo** [comment]
haha good call :P (pretty new to the whole "github OSS" thing hah)

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/Phildo/pixQL/commit/30959da67cece07c921694702d86a0e52e1c2f61).

Will any of the updated source files become a component for an application programming interface?

**Comment by Phildo** [comment]
> Will any of the updated source files become a component for an application programming interface?

I'm not sure I understand the question- are you wondering whether I intend on packaging pixQL as a library? I'm not sure. The project is too young to tell. But if I did, I think some serious code and even design refactoring would take place before doing so, so I don't want to get hung up on setting up the codebase as it currently stands for that kind of application just yet.

**Comment by elfring** [comment]
How do you think about the design of safe APIs and corresponding libraries for your application domain?

**Comment by Phildo** [comment]
I don't mean to offend, but I'm starting to think that maybe you're a bot connected to some kind of static analysis tool, hah.

I'm not _too_ worried about designing particularly safe APIs at this moment in time. As it currently exists, it is an experimental user-facing command line image editing tool, and that's it. It isn't intended to be connected to by any networks or given much opportunity for potentially malicious input.

For clarity's sake- I'm not saying "I don't care if pixQL isn't secure or well architected". I'm saying "I'm not yet worried about security or API extensibility at this point in the project's life".
