### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Phildo/pixQL#6]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) ⇒ [initTokens](https://github.com/Phildo/pixQL/blob/cba55d2abc93434dab5d6b046f4e58b6420fc249/token.c#L6)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [parseArgs](https://github.com/Phildo/pixQL/blob/0b8f8328fa172d915a65ea3e293f39dd835f2943/main.c#L16)

**Comment by Phildo** [comment]
Good call- will do later tonight. Thanks!

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/Phildo/pixQL/blob/02171b41fce7b264d81d1c3da62115763c790054/bitmap.c#L125) left over?
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by Phildo** [comment]
Good call on pointing out a few more places I could be more thorough in my error checking- will get right to it in a bit. Thanks!

I'll admit, I'm not familiar with aspect-oriented software development. A quick wikipedia skim yielded some interesting ideas regarding heuristics for abstraction, but I'm not too interested in conforming the codebase to any specific "orientation" at this time.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B) also for your software?

Do you find information sources like the following useful?
- Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking)"
- Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf)" by Johan Brichau and Theo D'Hondt
- Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164)" by Daniel Lohmann and Olaf Spinczyk
